# syntax=docker/dockerfile:1.4
FROM phusion/baseimage:jammy-1.0.1 as base

ENV DEBIAN_FRONTEND=noninteractive
RUN <<EOF
  apt-get update
  apt-get upgrade -y -o Dpkg::Options::="--force-confold"
  apt-get install -y postgresql-client
  apt-get clean
  rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/* /tmp/* /var/tmp/*
EOF

FROM base

COPY balance-tracker.sh /app/balance-tracker.sh
COPY <<EOF /etc/service/balance-tracker/run
#!/usr/bin/bash
set -e
cd /app
./balance-tracker.sh process-blocks
EOF
COPY <<EOF /app/healthcheck.sh
#!/usr/bin/bash
set -e
#Setup a trap to kill potentially pending healthcheck SQL query at script exit
#trap "trap - SIGTERM && kill -- -\$\$" SIGINT SIGTERM EXIT
source /etc/container_environment.sh
postgres_user=\${POSTGRES_USER:-"haf_admin"}
postgres_host=\${POSTGRES_HOST:-"localhost"}
postgres_port=\${POSTGRES_PORT:-5432}
postgres_url=\${POSTGRES_URL:-""}
POSTGRES_ACCESS=\${postgres_url:-"postgresql://\$postgres_user@\$postgres_host:\$postgres_port/haf_block_log"}
INSTANCE_READY=\$(psql "\$POSTGRES_ACCESS" --quiet --tuples-only --command="SELECT hive.is_instance_ready();")
[ \$INSTANCE_READY = f ] && exit 1
COMMAND="SELECT CASE WHEN (last_processed_block >= irreversible_block) and (irreversible_block > 0)  THEN 0 ELSE 1 END FROM btracker_app.app_status left join hive.contexts on (contexts.name = 'btracker_app') LIMIT 1;"
psql "\$POSTGRES_ACCESS" --quiet --tuples-only --command="\$COMMAND" | grep 0 &>/dev/null
EOF
RUN <<EOF
  chmod +x /etc/service/balance-tracker/run
  chmod +x /app/healthcheck.sh
EOF

# Processing of the blocks takes a long time (especially if haf is replaying), so
# set start-period to 3 days to avoid health check fail prior to that
HEALTHCHECK --interval=60s --timeout=5s --start-period=72h --retries=20 CMD [ "/app/healthcheck.sh" ]

# Process all the blocks and wait for new ones
ENV BLOCK_NUMBER 0

CMD ["/sbin/my_init"]
